[package]
name = "bitreader"
version = "0.3.2"
authors = ["Ilkka Rauta <ilkka.rauta@gmail.com>"]
edition = "2018"

description = """
BitReader helps reading individual bits from a slice of bytes.

You can read "unusual" numbers of bits from the byte slice, for example 13 bits
at once. The reader internally keeps track of position within the buffer.
"""

documentation = "https://docs.rs/bitreader"
homepage = "https://github.com/irauta/bitreader"
repository = "https://github.com/irauta/bitreader"

keywords = ["bit", "bits", "bitstream"]

license = "MIT OR Apache-2.0"

[dependencies]
cfg-if = "0.1.9"

[features]
std = []

default = ["std"]
